languageCode: en-us
baseURL: "https://horizonhou.github.io/"
title: Ruize Hou
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: RuizeHou
  description: "This is the website of **Ruize Hou**. I obtained MEng in Operations Research and Information Engineering @ Cornell. I love **Data Science**."
  keywords: [Blog, Portfolio, Data Science]
  author: Ruize Hou
  # author: ["Me", "You"] # multiple authors
  #images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  label:
    text: "Ruize Hou"
    icon: "images/data-science.png"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Welcome! \U0001F44B"
    subtitle: "Welcome to **Ruize Hou**'s page. I graduated from MEng Operations Research and Information Engineering (ORIE) @ **Cornell**,
    BS Applied Mathematics and Statistics @ **Emory**, Mathematics and Economics @ **RPI**.
    I Love **Data Science**, **Machine Learning**, and **Optimization**."
    imageUrl: "images/hrz1.jpg"
    imageWidth: 200
    imageHeight: 200
    imageTitle: "Horizon"
    buttons:
      - name: Blogs
        url: blogs
      - name: Projects
        url: projects
      - name: CV
        url: "https://drive.google.com/file/d/1gb1HZ2xvjIg2UsfPS8vYUnm-MAgAkjr9/preview"

  # home-info mode
  homeInfoParams:
    Title: "Welcome! \U0001F44B"
    Content: "This is the website of **Ruize Hou**, MEng in Operations Research and Information Engineering @ Cornell,
    Applied Math and Stats @ Emory, Math and Econ @ RPI.
    I Love **Data Science**."

  socialIcons:
    - name: bilibili
      url: "https://space.bilibili.com/14712754/"
    #- name: medium
      #url: "https://medium.com/@data-professor"
    #- name: twitter
      #url: "https://twitter.com/thedataprof"
    - name: linkedin
      url: "https://www.linkedin.com/in/ruize-hou/"
    - name: github
      url: "https://github.com/horizonhou/"
    - name: CV
      url: "https://drive.google.com/file/d/1gb1HZ2xvjIg2UsfPS8vYUnm-MAgAkjr9/preview"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page


  editPost:
#    URL: "https://github.com/chanin-www/content"
#    Text: "Suggest Changes" # edit text
    URL: ""
    Text: "" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 1
    - identifier: blog
      name: Blogs
      url: /blogs/
      weight: 3
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 2
    #- identifier: infographics
      #name: Infographics
      #url: /infographics/
      #weight: 3
    #- identifier: tags
    #  name: tags
    #  url: /tags/
    #  weight: 4

    #- identifier: example
    #  name: example.org
    #  url: https://example.org
    #  weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
